### ISSUE TITLE
Projeto está parado ?

### ISSUE THREAD

**Issue by ricardosierra** [tayron/project-manager#1]
Estava procurando gerenciadores de projetos em php, achei esse aqui mas vi que está muito tempo sem mexer nele.

Ainda tem interesse em seguir com o projeto ?

Achei uma outra solução na web
https://demo-tuleap.enalean.com

Obs: É em português mesmo, que aqui é BR, e BR é da zueira.

**Comment by tayron** [comment]
Boa tarde,

Não tenho interesse em continuar por agora não.. por isso deixei o código
aberto, para caso alguém queira ir fazendo melhorias nele e tal.

_Tayron Miranda_
Site Pessoal http://www.tayron.com.br - Linkedin
http://br.linkedin.com/in/tayronmiranda - Github
http://github.com/tayron - Twitter https://twitter.com/TayronMiranda
- http://www.vagacolaborativa.com.br/*

Em 11 de julho de 2016 15:41, Ricardo Sierra notifications@github.com
escreveu:
